services:
#service gérant le serveur
  server:
    image: node
    ports:
      - 3000:3000
    volumes:
      - ./code/server:/app
    working_dir: /app
    #commande pour garder le conteneur ouvert, vu que on va utiliser le terminale
    tty: true