services:
# service gérant le serveur web
  webserver:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/webserver/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/letsencrypt:/etc/letsencrypt
      - ./code/client:/app/client
      - ./code/server:/app/server
    working_dir: /app
  # service permettant de créer des certificats HTTPS
  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/letsencrypt:/etc/letsencrypt
# service gérant le client
  client:
    image: node:22
    volumes:
      - ./code/client:/app
    working_dir: /app
    #commande pour garder le conteneur ouvert, vu que on va utiliser le terminale
    tty: true
#service gérant le serveur
  server:
    image: node:22
    ports:
      - 3000:3000
    volumes:
      - ./code/server:/app
    working_dir: /app
    #commande pour garder le conteneur ouvert, vu que on va utiliser le terminale
    tty: true
  # service gérant le serveur mysql
  mysql:
    image: mysql:9
    ports:
      - 3306:3306
    volumes:
      - ./code/server/mysql:/app
      - ./mysql-db:/var/lib/mysql
    working_dir: /app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  # service gérant le serveur MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./code/server/mongodb:/app
      - ./mongodb-db:/data/db
    working_dir: /app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always

 
  