# nom du flux de travail / workflow
name: Garage CI/CD

# déclenchement du workflow
on: workflow_dispatch

# travail / job / taches
jobs:

    # nom de la tache
    CI:

        # exécuteur / runner
        runs-on: ubuntu-latest

        # étape / step
        steps:
        -
            name: Récupérer le dépot Github

            # éxécuter une action prédéfinie
            uses: actions/checkout@v4

        -
            name: Installer les dépendances de Node

            # éxecuter une commande personelle
            run: |
              cd code/server
              npm ci

        -
            name: Compiler TypeScript en JavaSript
            run: |
              cd code/server
              rm -rf dist
              npm run compile
        